name: Example workflow for Codecov

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        if [ -f requirements/coverage.txt ]; then pip install -r requirements/coverage.txt; fi
        pytest -q tests/ --cov=./app/ --cov-append --cov-report=term-missing --cov-fail-under=50 --cov-report=xml
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2