name: Example workflow for Codecov

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest -q tests/ --cov=./app/ --cov-append --cov-report=term-missing --cov-fail-under=50 --cov-report=xml
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2